# Generated by Django 3.2.6 on 2021-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
