# Generated by Django 3.2.6 on 2021-08-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0003_alter_vote_current_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='current_song',
        ),
    ]
